# Python Numpy

NumPy is a Python package stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful **n-dimensional array object**. NumPy array can also be used as an efficient multi-dimensional container for generic data.
<hr >

## Numpy Arrays & Matrices

**Numpy array** is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize numpy arrays from nested Python lists and access it elements.

- Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. 
- Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.

NumPy arrays are a bit like Python lists, but still very much different at the same time. 
<hr>

In [7]:
import numpy as np

In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
album_list=[["Thriller","Back in Black"],\
                        ["The Dark side of the Moon","The BodyGuard"], \
                        ["Bat Out of Hell","Their Greatest Hits(1971-1975)"],\
                        ["Saturday Night Fever","Rumours"]]
np.array(album_list)

array([['Thriller', 'Back in Black'],
       ['The Dark side of the Moon', 'The BodyGuard'],
       ['Bat Out of Hell', 'Their Greatest Hits(1971-1975)'],
       ['Saturday Night Fever', 'Rumours']], dtype='<U30')

### NumPy Array v/s Python List

Use python numpy array instead of a list because;

- Less Memory
- Fast
- Convenient

In [23]:
import numpy as np
import time
import sys

SIZE = 1000000
print("------------------------------------- Less Memory -------------------------------------")

S = range(SIZE)
print("Memory allocated to 10 Lakh size list is :" + str(sys.getsizeof(5)*len(S)))
 
D = np.arange(SIZE)
print("Memory allocated to 10 Lakh size numpy array is :" + str(D.size*D.itemsize))

print("\n------------------------------------- Fast -------------------------------------")

L1= range(SIZE)
L2= range(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print("Time taken 10 Lakh size of List :"  + str((time.time()-start)*1000))

A1= np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result= A1+A2
print("Time taken 10 Lakh size of Numpy array :"  + str((time.time()-start)*1000))

print("\n------------------------------------- convenient -------------------------------------")

# ‘for’ loop for a list which returns the concatenation of both the lists
# whereas for numpy arrays, we have just added the two array by simply printing A1+A2.

# That’s why working with numpy is much easier and convenient when compared to the lists.

------------------------------------- Less Memory -------------------------------------
Memory allocated to 10 Lakh size list is :28000000
Memory allocated to 10 Lakh size numpy array is :8000000

------------------------------------- Fast -------------------------------------
Time taken 10 Lakh size of List :134.63497161865234
Time taken 10 Lakh size of Numpy array :37.77742385864258

------------------------------------- convenient -------------------------------------


### NumPy Operations

In [12]:
import numpy as np

a = np.array([(1,2,3,4),(3,4,5,6)])
print(a.ndim)                        # find the dimension of the array
print(a.itemsize)                    # byte size of every element occupies in the numpy array.
print(a.dtype)                       # datatype of every element
print(a.size)
print(a[0,2])                        # extracting particular set of elements from an array.


a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

a=np.array([(1,2,3),(4,5,6)])
print(a.shape)                      # works with 2D array
print(a.reshape(3,2))               # transform rows * colum to columns * rows, works with 2D array


x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)

2
8
int64
8
3
1
3
6
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Data Frames 